// --- Text normalization ---

export function normalizeText(text) {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
}

// --- Keyword → category name dictionary ---
// Maps normalized Spanish keywords to category display names.
// The category name must match (after normalization) a category in the user's house.

const KEYWORD_TO_CATEGORY = {
  // ── Limpieza ──
  'jabon': 'Limpieza',
  'detergente': 'Limpieza',
  'cloro': 'Limpieza',
  'blanqueador': 'Limpieza',
  'desinfectante': 'Limpieza',
  'limpiador': 'Limpieza',
  'limpiavidrios': 'Limpieza',
  'multiusos': 'Limpieza',
  'quitagrasa': 'Limpieza',
  'desengrasante': 'Limpieza',
  'suavizante': 'Limpieza',
  'lavaplatos': 'Limpieza',
  'lavaloza': 'Limpieza',
  'lavavajillas': 'Limpieza',
  'lustramuebles': 'Limpieza',
  'cera': 'Limpieza',
  'aromatizante': 'Limpieza',
  'ambientador': 'Limpieza',
  'ajax': 'Limpieza',
  'fabuloso': 'Limpieza',
  'mistolin': 'Limpieza',
  'varsol': 'Limpieza',
  'thinner': 'Limpieza',
  'creolina': 'Limpieza',
  'pinesol': 'Limpieza',
  'poett': 'Limpieza',
  'clorox': 'Limpieza',
  'lejia': 'Limpieza',
  'limpia pisos': 'Limpieza',
  'limpiador de bano': 'Limpieza',
  'saca manchas': 'Limpieza',
  'quitamanchas': 'Limpieza',
  'removedor': 'Limpieza',
  'desodorizante': 'Limpieza',
  'antigrasa': 'Limpieza',
  'desincrustante': 'Limpieza',
  'descalcificador': 'Limpieza',
  'limpia hornos': 'Limpieza',
  'limpia cocina': 'Limpieza',
  'limpia inodoro': 'Limpieza',
  'pastilla inodoro': 'Limpieza',
  'naftalina': 'Limpieza',
  'insecticida': 'Limpieza',
  'mata cucarachas': 'Limpieza',
  'veneno ratas': 'Limpieza',
  'repelente': 'Limpieza',
  'raid': 'Limpieza',
  'baygon': 'Limpieza',

  // ── Herramientas de limpieza ──
  'escoba': 'Herramientas',
  'trapero': 'Herramientas',
  'trapeador': 'Herramientas',
  'fregona': 'Herramientas',
  'recogedor': 'Herramientas',
  'balde': 'Herramientas',
  'cubeta': 'Herramientas',
  'esponja': 'Herramientas',
  'estropajo': 'Herramientas',
  'fibra': 'Herramientas',
  'cepillo': 'Herramientas',
  'guantes': 'Herramientas',
  'mopa': 'Herramientas',
  'plumero': 'Herramientas',
  'aspiradora': 'Herramientas',
  'churrusco': 'Herramientas',
  'escurridor': 'Herramientas',
  'atomizador': 'Herramientas',
  'rodillo': 'Herramientas',
  'limpion': 'Herramientas',
  'bayeta': 'Herramientas',
  'trapo': 'Herramientas',
  'pano de cocina': 'Herramientas',
  'microfibra': 'Herramientas',
  'cepillo de bano': 'Herramientas',
  'escobilla': 'Herramientas',
  'pala': 'Herramientas',
  'colador': 'Herramientas',
  'ganchos': 'Herramientas',
  'pinzas ropa': 'Herramientas',
  'tendedero': 'Herramientas',
  'gancho ropa': 'Herramientas',

  // ── Papel y desechables ──
  'papel higienico': 'Papel',
  'papel toalla': 'Papel',
  'servilleta': 'Papel',
  'servilletas': 'Papel',
  'toalla de papel': 'Papel',
  'toallas humedas': 'Papel',
  'panuelos': 'Papel',
  'bolsa de basura': 'Papel',
  'bolsas de basura': 'Papel',
  'bolsa basura': 'Papel',
  'bolsas basura': 'Papel',
  'film': 'Papel',
  'aluminio': 'Papel',
  'papel aluminio': 'Papel',
  'plastico': 'Papel',
  'vasos desechables': 'Papel',
  'platos desechables': 'Papel',
  'cubiertos desechables': 'Papel',
  'pitillos': 'Papel',
  'popotes': 'Papel',
  'sorbetes': 'Papel',
  'papel vinipel': 'Papel',
  'vinipel': 'Papel',
  'stretch': 'Papel',
  'papel encerado': 'Papel',
  'papel para hornear': 'Papel',
  'filtro cafe': 'Papel',
  'filtros cafe': 'Papel',
  'bolsas zip': 'Papel',
  'bolsas hermeticas': 'Papel',
  'contenedores desechables': 'Papel',

  // ── Frutas y verduras ──
  'manzana': 'Frutas y Verduras',
  'manzanas': 'Frutas y Verduras',
  'banana': 'Frutas y Verduras',
  'banano': 'Frutas y Verduras',
  'platano': 'Frutas y Verduras',
  'naranja': 'Frutas y Verduras',
  'naranjas': 'Frutas y Verduras',
  'limon': 'Frutas y Verduras',
  'limones': 'Frutas y Verduras',
  'tomate': 'Frutas y Verduras',
  'tomates': 'Frutas y Verduras',
  'cebolla': 'Frutas y Verduras',
  'cebollas': 'Frutas y Verduras',
  'papa': 'Frutas y Verduras',
  'papas': 'Frutas y Verduras',
  'patata': 'Frutas y Verduras',
  'patatas': 'Frutas y Verduras',
  'zanahoria': 'Frutas y Verduras',
  'zanahorias': 'Frutas y Verduras',
  'lechuga': 'Frutas y Verduras',
  'aguacate': 'Frutas y Verduras',
  'palta': 'Frutas y Verduras',
  'ajo': 'Frutas y Verduras',
  'pimenton': 'Frutas y Verduras',
  'pepino': 'Frutas y Verduras',
  'espinaca': 'Frutas y Verduras',
  'brocoli': 'Frutas y Verduras',
  'fresa': 'Frutas y Verduras',
  'fresas': 'Frutas y Verduras',
  'uva': 'Frutas y Verduras',
  'uvas': 'Frutas y Verduras',
  'pera': 'Frutas y Verduras',
  'peras': 'Frutas y Verduras',
  'mango': 'Frutas y Verduras',
  'piña': 'Frutas y Verduras',
  'sandia': 'Frutas y Verduras',
  'melon': 'Frutas y Verduras',
  'mandarina': 'Frutas y Verduras',
  'cilantro': 'Frutas y Verduras',
  'perejil': 'Frutas y Verduras',
  'apio': 'Frutas y Verduras',
  'repollo': 'Frutas y Verduras',
  'coliflor': 'Frutas y Verduras',
  'mazorca': 'Frutas y Verduras',
  'choclo': 'Frutas y Verduras',
  'habichuela': 'Frutas y Verduras',
  'arveja': 'Frutas y Verduras',
  'guayaba': 'Frutas y Verduras',
  'papaya': 'Frutas y Verduras',
  'maracuya': 'Frutas y Verduras',
  'lulo': 'Frutas y Verduras',
  'mora': 'Frutas y Verduras',
  'durazno': 'Frutas y Verduras',
  'cereza': 'Frutas y Verduras',
  'kiwi': 'Frutas y Verduras',
  'coco': 'Frutas y Verduras',
  'granadilla': 'Frutas y Verduras',
  'curuba': 'Frutas y Verduras',
  'pitaya': 'Frutas y Verduras',
  'tamarindo': 'Frutas y Verduras',
  'ciruela': 'Frutas y Verduras',
  'frambuesa': 'Frutas y Verduras',
  'arandano': 'Frutas y Verduras',
  'arandanos': 'Frutas y Verduras',
  'champiñon': 'Frutas y Verduras',
  'champinon': 'Frutas y Verduras',
  'hongos': 'Frutas y Verduras',
  'calabaza': 'Frutas y Verduras',
  'calabacin': 'Frutas y Verduras',
  'zucchini': 'Frutas y Verduras',
  'berenjena': 'Frutas y Verduras',
  'acelga': 'Frutas y Verduras',
  'rucula': 'Frutas y Verduras',
  'albahaca': 'Frutas y Verduras',
  'menta': 'Frutas y Verduras',
  'romero': 'Frutas y Verduras',
  'tomillo': 'Frutas y Verduras',
  'jengibre': 'Frutas y Verduras',
  'batata': 'Frutas y Verduras',
  'yuca': 'Frutas y Verduras',
  'name': 'Frutas y Verduras',
  'platano verde': 'Frutas y Verduras',
  'platano maduro': 'Frutas y Verduras',
  'remolacha': 'Frutas y Verduras',
  'rabano': 'Frutas y Verduras',
  'nabo': 'Frutas y Verduras',
  'puerro': 'Frutas y Verduras',
  'cebolla larga': 'Frutas y Verduras',
  'cebolleta': 'Frutas y Verduras',
  'chile': 'Frutas y Verduras',
  'aji': 'Frutas y Verduras',
  'habanero': 'Frutas y Verduras',
  'jalapeño': 'Frutas y Verduras',

  // ── Despensa / Granos ──
  'arroz': 'Despensa',
  'pasta': 'Despensa',
  'fideos': 'Despensa',
  'espagueti': 'Despensa',
  'lenteja': 'Despensa',
  'lentejas': 'Despensa',
  'frijol': 'Despensa',
  'frijoles': 'Despensa',
  'garbanzo': 'Despensa',
  'garbanzos': 'Despensa',
  'avena': 'Despensa',
  'cereal': 'Despensa',
  'harina': 'Despensa',
  'azucar': 'Despensa',
  'sal': 'Despensa',
  'aceite': 'Despensa',
  'vinagre': 'Despensa',
  'salsa de tomate': 'Despensa',
  'salsa': 'Despensa',
  'mayonesa': 'Despensa',
  'mostaza': 'Despensa',
  'ketchup': 'Despensa',
  'atun': 'Despensa',
  'sardina': 'Despensa',
  'sardinas': 'Despensa',
  'galletas': 'Despensa',
  'pan': 'Despensa',
  'panela': 'Despensa',
  'cafe': 'Despensa',
  'te': 'Despensa',
  'chocolate': 'Despensa',
  'miel': 'Despensa',
  'mermelada': 'Despensa',
  'granola': 'Despensa',
  'maiz': 'Despensa',
  'arepa': 'Despensa',
  'arepas': 'Despensa',
  'tortilla': 'Despensa',
  'tortillas': 'Despensa',
  'condimento': 'Despensa',
  'pimienta': 'Despensa',
  'comino': 'Despensa',
  'oregano': 'Despensa',
  'canela': 'Despensa',
  'caldo': 'Despensa',
  'consomé': 'Despensa',
  'sazon': 'Despensa',
  'triguisar': 'Despensa',
  'color': 'Despensa',
  'achiote': 'Despensa',
  'paprika': 'Despensa',
  'curry': 'Despensa',
  'laurel': 'Despensa',
  'nuez moscada': 'Despensa',
  'clavo': 'Despensa',
  'cubito': 'Despensa',
  'maggi': 'Despensa',
  'knorr': 'Despensa',
  'doña gallina': 'Despensa',
  'salsa soya': 'Despensa',
  'salsa soja': 'Despensa',
  'salsa inglesa': 'Despensa',
  'salsa bbq': 'Despensa',
  'salsa picante': 'Despensa',
  'tabasco': 'Despensa',
  'sriracha': 'Despensa',
  'aceite de oliva': 'Despensa',
  'aceite vegetal': 'Despensa',
  'aceite de coco': 'Despensa',
  'manteca': 'Despensa',
  'vinagre balsamico': 'Despensa',
  'maicena': 'Despensa',
  'fecula': 'Despensa',
  'levadura': 'Despensa',
  'polvo de hornear': 'Despensa',
  'bicarbonato': 'Despensa',
  'gelatina': 'Despensa',
  'pudding': 'Despensa',
  'flan': 'Despensa',
  'leche condensada': 'Despensa',
  'leche evaporada': 'Despensa',
  'leche en polvo': 'Despensa',
  'cocoa': 'Despensa',
  'masmelo': 'Despensa',
  'malvavisco': 'Despensa',
  'dulce de leche': 'Despensa',
  'arequipe': 'Despensa',
  'nutella': 'Despensa',
  'crema de mani': 'Despensa',
  'mantequilla de mani': 'Despensa',
  'mani': 'Despensa',
  'nuez': 'Despensa',
  'nueces': 'Despensa',
  'almendra': 'Despensa',
  'almendras': 'Despensa',
  'pasas': 'Despensa',
  'semillas': 'Despensa',
  'linaza': 'Despensa',
  'chia': 'Despensa',
  'quinoa': 'Despensa',
  'cuscus': 'Despensa',
  'palomitas': 'Despensa',
  'crispetas': 'Despensa',
  'harina de trigo': 'Despensa',
  'harina pan': 'Despensa',
  'harina de maiz': 'Despensa',
  'sopa instantanea': 'Despensa',
  'ramen': 'Despensa',
  'aceitunas': 'Despensa',
  'alcaparras': 'Despensa',
  'encurtidos': 'Despensa',
  'pepinillos': 'Despensa',
  'maiz enlatado': 'Despensa',
  'durazno en lata': 'Despensa',
  'frijoles enlatados': 'Despensa',
  'leche de coco': 'Despensa',
  'pasta de tomate': 'Despensa',
  'tomate enlatado': 'Despensa',

  // ── Snacks y dulces ──
  'papas fritas': 'Snacks',
  'chips': 'Snacks',
  'nachos': 'Snacks',
  'doritos': 'Snacks',
  'cheetos': 'Snacks',
  'chitos': 'Snacks',
  'de todito': 'Snacks',
  'mani salado': 'Snacks',
  'frutos secos': 'Snacks',
  'chocolatina': 'Snacks',
  'chicle': 'Snacks',
  'chicles': 'Snacks',
  'gomitas': 'Snacks',
  'colombina': 'Snacks',
  'bombones': 'Snacks',
  'caramelos': 'Snacks',
  'dulces': 'Snacks',
  'brownie': 'Snacks',
  'ponque': 'Snacks',
  'torta': 'Snacks',
  'barras de cereal': 'Snacks',
  'barra de cereal': 'Snacks',
  'galletas oreo': 'Snacks',
  'galletas festival': 'Snacks',
  'wafer': 'Snacks',
  'bocadillo': 'Snacks',
  'obleas': 'Snacks',

  // ── Lacteos y refrigerados ──
  'leche': 'Lacteos',
  'queso': 'Lacteos',
  'yogur': 'Lacteos',
  'yogurt': 'Lacteos',
  'mantequilla': 'Lacteos',
  'margarina': 'Lacteos',
  'crema de leche': 'Lacteos',
  'crema': 'Lacteos',
  'huevo': 'Lacteos',
  'huevos': 'Lacteos',
  'queso crema': 'Lacteos',
  'queso rallado': 'Lacteos',
  'queso parmesano': 'Lacteos',
  'queso mozarella': 'Lacteos',
  'queso campesino': 'Lacteos',
  'queso costeño': 'Lacteos',
  'kumis': 'Lacteos',
  'avena alpina': 'Lacteos',
  'leche deslactosada': 'Lacteos',
  'leche de almendras': 'Lacteos',
  'leche de soya': 'Lacteos',
  'leche de avena': 'Lacteos',
  'tofu': 'Lacteos',
  'nata': 'Lacteos',

  // ── Carnes y proteinas ──
  'pollo': 'Carnes',
  'pechuga': 'Carnes',
  'carne': 'Carnes',
  'carne molida': 'Carnes',
  'res': 'Carnes',
  'cerdo': 'Carnes',
  'chorizo': 'Carnes',
  'salchicha': 'Carnes',
  'salchichas': 'Carnes',
  'jamon': 'Carnes',
  'tocino': 'Carnes',
  'tocineta': 'Carnes',
  'pescado': 'Carnes',
  'salmon': 'Carnes',
  'camaron': 'Carnes',
  'camarones': 'Carnes',
  'mariscos': 'Carnes',
  'costilla': 'Carnes',
  'costillas': 'Carnes',
  'lomo': 'Carnes',
  'chuleta': 'Carnes',
  'chuletas': 'Carnes',
  'bistec': 'Carnes',
  'filete': 'Carnes',
  'milanesa': 'Carnes',
  'mortadela': 'Carnes',
  'salami': 'Carnes',
  'pepperoni': 'Carnes',
  'alas de pollo': 'Carnes',
  'muslo': 'Carnes',
  'muslos': 'Carnes',
  'pierna de pollo': 'Carnes',
  'menudencias': 'Carnes',
  'higado': 'Carnes',
  'mollejas': 'Carnes',
  'chicharron': 'Carnes',
  'morcilla': 'Carnes',
  'longaniza': 'Carnes',
  'butifarra': 'Carnes',
  'trucha': 'Carnes',
  'tilapia': 'Carnes',
  'atun fresco': 'Carnes',
  'pulpo': 'Carnes',
  'calamar': 'Carnes',
  'almejas': 'Carnes',
  'mejillones': 'Carnes',
  'cangrejo': 'Carnes',
  'langostino': 'Carnes',

  // ── Bebidas ──
  'agua': 'Bebidas',
  'jugo': 'Bebidas',
  'gaseosa': 'Bebidas',
  'refresco': 'Bebidas',
  'cerveza': 'Bebidas',
  'vino': 'Bebidas',
  'soda': 'Bebidas',
  'limonada': 'Bebidas',
  'coca cola': 'Bebidas',
  'pepsi': 'Bebidas',
  'sprite': 'Bebidas',
  'fanta': 'Bebidas',
  'postobon': 'Bebidas',
  'agua con gas': 'Bebidas',
  'agua mineral': 'Bebidas',
  'te helado': 'Bebidas',
  'te frio': 'Bebidas',
  'energizante': 'Bebidas',
  'red bull': 'Bebidas',
  'vive 100': 'Bebidas',
  'gatorade': 'Bebidas',
  'powerade': 'Bebidas',
  'leche de chocolate': 'Bebidas',
  'malteada': 'Bebidas',
  'aguardiante': 'Bebidas',
  'aguardiente': 'Bebidas',
  'ron': 'Bebidas',
  'whisky': 'Bebidas',
  'vodka': 'Bebidas',
  'tequila': 'Bebidas',
  'licor': 'Bebidas',
  'jugo de naranja': 'Bebidas',
  'jugo de manzana': 'Bebidas',
  'pulpa de fruta': 'Bebidas',
  'tang': 'Bebidas',
  'frutiño': 'Bebidas',

  // ── Higiene personal ──
  'shampoo': 'Higiene',
  'champu': 'Higiene',
  'acondicionador': 'Higiene',
  'jabon de bano': 'Higiene',
  'gel de ducha': 'Higiene',
  'desodorante': 'Higiene',
  'crema dental': 'Higiene',
  'pasta dental': 'Higiene',
  'cepillo de dientes': 'Higiene',
  'hilo dental': 'Higiene',
  'enjuague bucal': 'Higiene',
  'rastrillo': 'Higiene',
  'cuchilla': 'Higiene',
  'cuchillas': 'Higiene',
  'protector solar': 'Higiene',
  'bloqueador': 'Higiene',
  'crema corporal': 'Higiene',
  'algodon': 'Higiene',
  'cotonetes': 'Higiene',
  'copitos': 'Higiene',
  'toallas sanitarias': 'Higiene',
  'tampones': 'Higiene',
  'pañales': 'Higiene',
  'panales': 'Higiene',
  'jabon liquido': 'Higiene',
  'gel antibacterial': 'Higiene',
  'antibacterial': 'Higiene',
  'crema de manos': 'Higiene',
  'locion': 'Higiene',
  'perfume': 'Higiene',
  'colonia': 'Higiene',
  'talco': 'Higiene',
  'vaselina': 'Higiene',
  'removedor de esmalte': 'Higiene',
  'esmalte': 'Higiene',
  'lima de unas': 'Higiene',
  'cortaunas': 'Higiene',
  'pinzas': 'Higiene',
  'cera depilatoria': 'Higiene',
  'tinte de cabello': 'Higiene',
  'tinte': 'Higiene',
  'fijador': 'Higiene',
  'gel para cabello': 'Higiene',
  'laca': 'Higiene',
  'mousse': 'Higiene',
  'crema para peinar': 'Higiene',
  'tratamiento capilar': 'Higiene',
  'protectores diarios': 'Higiene',
  'copa menstrual': 'Higiene',

  // ── Bebe ──
  'formula': 'Bebe',
  'formula bebe': 'Bebe',
  'leche de formula': 'Bebe',
  'panales bebe': 'Bebe',
  'toallitas bebe': 'Bebe',
  'toallitas humedas bebe': 'Bebe',
  'crema antipanalitis': 'Bebe',
  'crema de pañal': 'Bebe',
  'tetero': 'Bebe',
  'biberon': 'Bebe',
  'chupo': 'Bebe',
  'chupete': 'Bebe',
  'papilla': 'Bebe',
  'compota': 'Bebe',
  'colado': 'Bebe',
  'cereal bebe': 'Bebe',
  'shampoo bebe': 'Bebe',
  'jabon bebe': 'Bebe',

  // ── Mascotas ──
  'comida para perro': 'Mascotas',
  'comida para gato': 'Mascotas',
  'concentrado': 'Mascotas',
  'arena para gato': 'Mascotas',
  'arena gato': 'Mascotas',
  'cuido': 'Mascotas',
  'dog chow': 'Mascotas',
  'cat chow': 'Mascotas',
  'perrarina': 'Mascotas',
  'gatarina': 'Mascotas',
  'pedigree': 'Mascotas',
  'whiskas': 'Mascotas',
  'purina': 'Mascotas',
  'ringo': 'Mascotas',
  'chunky': 'Mascotas',
  'snack para perro': 'Mascotas',
  'hueso para perro': 'Mascotas',
  'antipulgas': 'Mascotas',
  'shampoo para perro': 'Mascotas',
  'collar antipulgas': 'Mascotas',
  'correa para perro': 'Mascotas',
  'juguete para perro': 'Mascotas',
  'comedero': 'Mascotas',
  'bebedero': 'Mascotas',
  'pecera': 'Mascotas',
  'comida para pez': 'Mascotas',

  // ── Salud / Medicamentos ──
  'acetaminofen': 'Salud',
  'ibuprofeno': 'Salud',
  'aspirina': 'Salud',
  'alcohol': 'Salud',
  'agua oxigenada': 'Salud',
  'curitas': 'Salud',
  'banditas': 'Salud',
  'vitaminas': 'Salud',
  'antigripal': 'Salud',
  'pastillas': 'Salud',
  'jarabe': 'Salud',
  'termometro': 'Salud',
  'gasa': 'Salud',
  'venda': 'Salud',
  'vendas': 'Salud',
  'esparadrapo': 'Salud',
  'micropore': 'Salud',
  'suero oral': 'Salud',
  'suero': 'Salud',
  'antiacido': 'Salud',
  'sal de frutas': 'Salud',
  'omeprazol': 'Salud',
  'loratadina': 'Salud',
  'antialergico': 'Salud',
  'antidiarreico': 'Salud',
  'laxante': 'Salud',
  'gotas para ojos': 'Salud',
  'gotas nasales': 'Salud',
  'descongestionante': 'Salud',
  'crema para dolor': 'Salud',
  'balsamo': 'Salud',
  'mentol': 'Salud',
  'vick vaporub': 'Salud',
  'isodine': 'Salud',
  'yodo': 'Salud',
  'tapabocas': 'Salud',
  'mascarilla': 'Salud',
  'preservativos': 'Salud',
  'condones': 'Salud',
  'test embarazo': 'Salud',
  'tension': 'Salud',
  'oximetro': 'Salud',

  // ── Congelados ──
  'helado': 'Congelados',
  'pizza': 'Congelados',
  'papas congeladas': 'Congelados',
  'nuggets': 'Congelados',
  'empanadas': 'Congelados',
  'deditos de queso': 'Congelados',
  'arepas congeladas': 'Congelados',
  'pan congelado': 'Congelados',
  'hamburguesas congeladas': 'Congelados',
  'palitos de pescado': 'Congelados',
  'verduras congeladas': 'Congelados',
  'fruta congelada': 'Congelados',
  'hielo': 'Congelados',

  // ── Panaderia ──
  'pan tajado': 'Panaderia',
  'pan integral': 'Panaderia',
  'mogolla': 'Panaderia',
  'croissant': 'Panaderia',
  'tostadas': 'Panaderia',
  'pan blanco': 'Panaderia',
  'pan de molde': 'Panaderia',
  'pan arabe': 'Panaderia',
  'pan pita': 'Panaderia',
  'pan baguette': 'Panaderia',
  'buñuelo': 'Panaderia',
  'pandebono': 'Panaderia',
  'pan de bono': 'Panaderia',
  'almojabana': 'Panaderia',
  'donut': 'Panaderia',
  'dona': 'Panaderia',
  'muffin': 'Panaderia',
  'cupcake': 'Panaderia',
  'pastel': 'Panaderia',

  // ── Hogar ──
  'bombillo': 'Hogar',
  'bombilla': 'Hogar',
  'foco': 'Hogar',
  'pilas': 'Hogar',
  'baterias': 'Hogar',
  'velas': 'Hogar',
  'fosforos': 'Hogar',
  'encendedor': 'Hogar',
  'extension electrica': 'Hogar',
  'adaptador': 'Hogar',
  'cinta pegante': 'Hogar',
  'cinta aislante': 'Hogar',
  'pegamento': 'Hogar',
  'silicona': 'Hogar',
  'tornillos': 'Hogar',
  'clavos': 'Hogar',
  'candado': 'Hogar',
  'cerradura': 'Hogar',
  'llave': 'Hogar',
  'destornillador': 'Hogar',
  'martillo': 'Hogar',
  'alicate': 'Hogar',
  'cinta de enmascarar': 'Hogar',
  'pintura': 'Hogar',
  'brocha': 'Hogar',
  'lija': 'Hogar',
  'cable': 'Hogar',
  'enchufe': 'Hogar',
  'fusible': 'Hogar',
  'cortina': 'Hogar',
  'cortinas': 'Hogar',
  'gancho cortina': 'Hogar',
  'toalla': 'Hogar',
  'toallas': 'Hogar',
  'sabanas': 'Hogar',
  'almohada': 'Hogar',
  'cobija': 'Hogar',
  'edredon': 'Hogar',
  'tapete': 'Hogar',
  'alfombra': 'Hogar',
  'organizador': 'Hogar',
  'canasta': 'Hogar',
  'cesto': 'Hogar',
  'percha': 'Hogar',
  'perchas': 'Hogar',

  // ── Oficina / Escolar ──
  'cuaderno': 'Oficina',
  'cuadernos': 'Oficina',
  'lapicero': 'Oficina',
  'lapiceros': 'Oficina',
  'esfero': 'Oficina',
  'lapiz': 'Oficina',
  'lapices': 'Oficina',
  'borrador': 'Oficina',
  'sacapuntas': 'Oficina',
  'regla': 'Oficina',
  'tijeras': 'Oficina',
  'colores': 'Oficina',
  'marcadores': 'Oficina',
  'marcador': 'Oficina',
  'resaltador': 'Oficina',
  'carpeta': 'Oficina',
  'folder': 'Oficina',
  'sobre': 'Oficina',
  'papel carta': 'Oficina',
  'papel bond': 'Oficina',
  'hojas': 'Oficina',
  'impresora': 'Oficina',
  'tinta': 'Oficina',
  'grapadora': 'Oficina',
  'grapas': 'Oficina',
  'clips': 'Oficina',
  'post it': 'Oficina',
  'notas adhesivas': 'Oficina',
  'cinta transparente': 'Oficina',
  'corrector': 'Oficina',
  'liquid paper': 'Oficina',
  'agenda': 'Oficina',
  'calculadora': 'Oficina',
  'mochila': 'Oficina',
  'morral': 'Oficina',
  'lonchera': 'Oficina',
  'termo': 'Oficina',
}

// Pre-compute normalized keys for faster lookup
const NORMALIZED_ENTRIES = Object.entries(KEYWORD_TO_CATEGORY).map(
  ([keyword, category]) => [normalizeText(keyword), category]
)

// Sort by keyword length descending so longer (more specific) matches win
NORMALIZED_ENTRIES.sort((a, b) => b[0].length - a[0].length)

// --- Suggestion logic ---

export function suggestCategory(inputText, categories) {
  if (!inputText || !categories || categories.length === 0) return null

  const normalized = normalizeText(inputText)
  if (!normalized) return null

  // Two-pass matching: direct match first (input contains keyword),
  // then inverse match as fallback (keyword contains input, for partial typing).
  // This prevents long compound keywords like "jugo de manzana" (Bebidas)
  // from hijacking simple inputs like "manzana" (Frutas y Verduras).
  let matchedCategoryName = null
  for (const [keyword, categoryName] of NORMALIZED_ENTRIES) {
    if (normalized.includes(keyword)) {
      matchedCategoryName = categoryName
      break
    }
  }
  if (!matchedCategoryName) {
    for (const [keyword, categoryName] of NORMALIZED_ENTRIES) {
      if (keyword.includes(normalized)) {
        matchedCategoryName = categoryName
        break
      }
    }
  }

  if (!matchedCategoryName) return null

  // Find matching category in house's categories (flexible substring match)
  const normalizedMatch = normalizeText(matchedCategoryName)
  const category = categories.find(cat => {
    const normalizedCat = normalizeText(cat.name)
    return normalizedCat.includes(normalizedMatch) || normalizedMatch.includes(normalizedCat)
  })

  return category ? { id: category.id, name: category.name, emoji: category.emoji } : null
}
